package GameObjects;

import java.util.UUID;

import processing.core.PApplet;

public class Bullet extends Movable{

	// friendly is used to described a bullet
	// if a bullet is friendly, then it is generated by the players' gun turret,
	// and its yspeed < 0; Also, it can only collided with ships
	// if a bullet is unfriendly, then it is generated by ships,
	//	its yspeed > 0, and it can only collided with gun turrets
	public boolean friendly;
	
	public Bullet(PApplet p, float x, float y, boolean friendly) {
		id = UUID.randomUUID();
		parent = p;
		this.x = x;
		this.y = y;
		this.friendly = friendly;
		xspeed = 0;
		if(friendly) {
			yspeed = -1;
		}else {
			yspeed = 1;
		}
	}
	
	@Override
	public void move() {
		y += (yspeed*frameDuration);
	}

	@Override
	public void show() {
		parent.noStroke();
		parent.fill(0);
		parent.rect(x, y, 6, 20);
	}

}
